-- MySQL Script generated by MySQL Workbench
-- sáb 09 jul 2016 02:16:42 ART
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema farmacia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema farmacia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `farmacia` DEFAULT CHARACTER SET utf8 ;
USE `farmacia` ;

-- -----------------------------------------------------
-- Table `farmacia`.`farmacia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`farmacia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(1500) NULL,
  `direccion` VARCHAR(1500) NULL,
  `telefono` VARCHAR(1500) NULL,
  `urlMaps` VARCHAR(1500) NULL,
  `urlWeb` VARCHAR(1500) NULL,
  `coords` VARCHAR(1500) NULL,
  `latitud` VARCHAR(1500) NULL,
  `longitud` VARCHAR (1500) NULL,
  `horario` VARCHAR(1500) NULL,
  `observaciones` VARCHAR(1500) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`tipo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `letra` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`farmacia_has_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`farmacia_has_tipo` (
  `farmacia_id` INT NOT NULL,
  `tipo_idtipo` INT NOT NULL,
  PRIMARY KEY (`farmacia_id`, `tipo_idtipo`),
  INDEX `fk_farmacia_has_tipo_tipo1_idx` (`tipo_idtipo` ASC),
  INDEX `fk_farmacia_has_tipo_farmacia_idx` (`farmacia_id` ASC),
  CONSTRAINT `fk_farmacia_has_tipo_farmacia`
    FOREIGN KEY (`farmacia_id`)
    REFERENCES `farmacia`.`farmacia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_farmacia_has_tipo_tipo1`
    FOREIGN KEY (`tipo_idtipo`)
    REFERENCES `farmacia`.`tipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
