-- MySQL Script generated by MySQL Workbench
-- vie 08 jul 2016 19:57:09 ART
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema farmacia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema farmacia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `farmacia` DEFAULT CHARACTER SET utf8 ;
USE `farmacia` ;

-- -----------------------------------------------------
-- Table `farmacia`.`farmacia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`farmacia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `urlMaps` VARCHAR(45) NULL,
  `urlWeb` VARCHAR(45) NULL,
  `coords` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `farmacia`.`tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `farmacia`.`tipo` (
  `farmacia_id` INT NOT NULL,
  `tipo` VARCHAR(45) NULL,
  INDEX `fk_tipo_farmacia_idx` (`farmacia_id` ASC),
  CONSTRAINT `fk_tipo_farmacia`
    FOREIGN KEY (`farmacia_id`)
    REFERENCES `farmacia`.`farmacia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
